export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const NAVIGATE_HOME = 'NAVIGATE_HOME';

export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';

export const CHANGE_PAGE = 'CHANGE_PAGE';
